spanbert_base:
  bert_config_file: /data/nfsdata/nlp/BERT_BASE_DIR/cased_L-12_H-768_A-12/bert_config.json
  dropout_rate: 0.3
  span_ratio: 0.2
  max_candidate_num: 3900
  max_antecedent_num: 50
  max_span_width: 10
  sliding_window_size: 384
  pad_idx: -4
  use_span_width_embeddings: true
  span_width_embed_size: 1024
  ffnn_size: 1024
  ffnn_depth: 1
  mention_start_idx: 37
  mention_end_idx: 42
  speaker_start_idx: 19
  speaker_end_idx: 73
  max_question_len: 128

  num_epochs: 10
  num_docs: 2802
  save_checkpoints_steps: 500
  init_checkpoint: false
  train_file: /data/nfs/wuwei/study/CorefQA/data/train.english.tfrecord

  bert_init_lr: 0.00001
  task_init_lr: 0.00001
  bert_opt: adam_weight_decay
  task_opt: adam_weight_decay
  freeze: -1
  warmup_ratio: 0.1